### PR TITLE
Update blacklist.sh

### PR DESCRIPTION
**Pull request by mary-cordova**
updating comment for shadow server to new source name
updating shadowserver compatibility with file format change
adding comment regarding prips installation
removing discontinued palevo
adding new ransomware tracker

### CODE REVIEW

**Comment by mary-cordova** [comment]
Hi Vincent, wondering about modifying the behavior of the blacklist script
a little bit and wanted your input.

Here is the context:

   1. we use this with splunk
   2. the script appends the new blacklist (on a schedule) to the end of
   the current blacklist

Issues:

   1. the output blacklist files get to be very big (we have one that is
   4GB - I took over so I dont know how long we've been using the script but
   it has been since at least October)
   2. there are duplicates in the blacklist

Proposals and thinking:

   1. just output the new blacklist and overwrite the file do not append
      1. keeps file size down
      2. splunk re-ingests the entire file everytime
      3. there will be duplicates - but then there are already duplicates
      anyway
      4. ***lose historical record of previous IPs if they drop off the
      blacklist*** - I think this is the biggest issue to be avoided
   2. my idea instead of append or overwrite - | sort | uniq
      1. keeps file size down
      2. can take up to ~2min on large files - I ran this on the 4GB file
      and it brought it down to about 1GB (and would take less than 2min if ran
      consistently so files didnt grow so large)
      3. preserves history
      4. suppresses duplicates
      5. splunk will re-ingest the entire file - so there will be
      duplicates in splunk - but then there are already anyway :)

To do this, assuming Splunk is monitoring the .txt files, I used .tmp as
the appended files in the main body of the script and for the
sorting/deduping then moved them to the .txt extension for Splunk to ingest.

Here is a sample:

for i in `ls /etc/suricata/iprep/*.tmp | sed s/\.tmp//g`
do
cat $i.tmp | sort | uniq > $i.txt
yes | rm /etc/suricata/iprep/*.tmp
done


What do you think of this idea?  I will add to to your script and put in
another pull request and you can take it if you want or not :)  (We use a
different directory structure so I've tested on my side but you will
obviously want to test on yours.)


Cheers!
Mary

**Comment by shift** [comment]
If performance is a huge concern the following may be quicker to dedupe the input:
```
awk '!seen[$0]++' output
```

**Comment by mary-cordova** [comment]
thanks for the suggestion that works awesome(ly) i made some modifications
and uploaded to github - and i swear now im done messing with your stuff! :D

**Comment by shift** [comment]
Not a problem. PR's always welcomed 😄

**Pull request merged**
